// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ErwinMayerLabs.RenameVSWindowTitle
{
    static class Vsix
    {
        public const string Id = "5126c493-138a-46d7-a04d-ad772f6be159";
        public const string Name = "PSCustomize Visual Studio Window Title";
        public const string Description = @"This lightweight extension allows changing the window title of Visual Studio to include a folder tree with a configurable min depth and max depth distance from the solution/project file, and the use of special tags to help with many other possible scenarios (Git, Hg, TFS, SVN...). 
Solution-specific overriding rules are available as well to cover virtually any possible renaming needs. It can also be configured so that the rules apply only when at least two instances of Visual Studio are running with the same window title.
This is particularly useful when branching a solution/project: it becomes possible to easily identify which branch you are working on, in case both would have the same solution/project name.";
        public const string Language = "en-US";
        public const string Version = "4.4.0";
        public const string Author = "Erwin Mayer";
        public const string Tags = "Git, Hg, TFS, Team Foundation Server, SVN, Window title, solution path, path, explicit title, multiple instances, rename title, change title, replace title, branch name";
    }
}
