//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErwinMayerLabs.RenameVSWindowTitle {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErwinMayerLabs.RenameVSWindowTitle.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! normalize.css v4.1.1 | MIT License | github.com/necolas/normalize.css */
        ///
        ////**
        /// * 1. Change the default font family in all browsers (opinionated).
        /// * 2. Prevent adjustments of font size after orientation changes in IE and iOS.
        /// */
        ///
        ///html {
        ///  font-family: sans-serif; /* 1 */
        ///  -ms-text-size-adjust: 100%; /* 2 */
        ///  -webkit-text-size-adjust: 100%; /* 2 */
        ///}
        ///
        ////**
        /// * Remove the margin in all browsers (opinionated).
        /// */
        ///
        ///body {
        ///  margin: 0;
        ///}
        ///
        ////* HTML5 display definitions
        ///   ============== [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string normalize {
            get {
                return ResourceManager.GetString("normalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //http://stackoverflow.com/questions/200162/allow-only-copy-paste-context-menu-in-system-windows-forms-webbrowser-control/200194#200194
        /////&lt;div id=&apos;ContextMenu&apos; style=&apos;display: none; z-index: 1000; padding: 1px 10px; background-color: white; border: 2px solid lightgreen; position: absolute;&apos;&gt;&lt;a href=&apos;#&apos; id=&apos;CopyBtn&apos; style=&apos;display: block; color: black; text-decoration: none;&apos;&gt;Copy&lt;/a&gt;&lt;/div&gt;
        ///
        ///function selectText(obj) { // adapted from Denis Sadowski (via StackOverflow.com)
        ///    var range;
        ///    if (document [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string script {
            get {
                return ResourceManager.GetString("script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///    background: #fafafa;
        ///    color: #333;
        ///    font: 100%/30px &apos;Helvetica Neue&apos;, helvetica, arial, sans-serif;
        ///    margin: 8px;
        ///}
        ///
        ////*h1 {
        ///  font-size: 15pt;
        ///  margin-bottom: 10px;
        ///  font-weight: bold;
        ///}*/
        ///
        ///h2 {
        ///    font-size: 1.2em;
        ///    text-align: center;
        ///    margin-top: 0em;
        ///    margin-bottom: 0.2em;
        ///}
        ///
        ///strong {
        ///    font-weight: bold;
        ///}
        ///
        ///em {
        ///    font-style: italic;
        ///}
        ///
        ///table {
        ///    background: #f5f5f5;
        ///    font-size: 10pt;
        ///    line-height: 22px;
        ///    text-align: left;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current configuration name (e.g. Release)..
        /// </summary>
        internal static string tag_configurationName {
            get {
                return ResourceManager.GetString("tag_configurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active document or, if no active document, window name..
        /// </summary>
        internal static string tag_documentName {
            get {
                return ResourceManager.GetString("tag_documentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active document path parent element at the specified index (e.g. for C:\F1\Foo.cs, [parent:0] = Foo.cs [parent:1] = F1).
        /// </summary>
        internal static string tag_documentParentPathX {
            get {
                return ResourceManager.GetString("tag_documentParentPathX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active document path parent segment over the specified range (e.g. for C:\F1\Foo.cs, [parent:1:0] =F1\Foo.cs, [parent:0:1] = Foo.cs\F1).
        /// </summary>
        internal static string tag_documentParentPathXY {
            get {
                return ResourceManager.GetString("tag_documentParentPathXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active document full path or, if no active document, window name..
        /// </summary>
        internal static string tag_documentPath {
            get {
                return ResourceManager.GetString("tag_documentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active document path element at the specified index (e.g. for C:\F1\Foo.cs, [documentPath:0] = C:\, [documentPath:1] = C:\F1)..
        /// </summary>
        internal static string tag_documentPathX {
            get {
                return ResourceManager.GetString("tag_documentPathX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active document path segment over the specified range (e.g. for C:\F1\Foo.cs, [path:0:2] = C:\F1\Foo.cs, [path:2:0] = Foo.cs\F1\C:).
        /// </summary>
        internal static string tag_documentPathXY {
            get {
                return ResourceManager.GetString("tag_documentPathXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Git branch name. Make sure Git\&apos;s executable directory is added to the Windows PATH variable or specify its location in settings..
        /// </summary>
        internal static string tag_gitBranchName {
            get {
                return ResourceManager.GetString("tag_gitBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the IDE (e.g. Microsoft Visual Studio)..
        /// </summary>
        internal static string tag_ideName {
            get {
                return ResourceManager.GetString("tag_ideName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current solution path or, if no solution open, document path, with depth determined by &quot;Farthest parent folder depth&quot; and &quot;Closest parent folder depth&quot; settings..
        /// </summary>
        internal static string tag_parentPath {
            get {
                return ResourceManager.GetString("tag_parentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path parent element at the specified index (e.g. for C:\F1\MySolutionFolder\MySolution.sln, [parent:0] = MySolution.sln [parent:1] = MySolutionFolder).
        /// </summary>
        internal static string tag_parentX {
            get {
                return ResourceManager.GetString("tag_parentX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path parent segment over the specified range (e.g. for C:\F1\MySolutionFolder\MySolution.sln, [parent:2:1] =F1\MySolutionFolder, [parent:1:2] = MySolutionFolder\F1).
        /// </summary>
        internal static string tag_parentXY {
            get {
                return ResourceManager.GetString("tag_parentXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current solution full path or, if no solution open, document full path or, if no active document, window name..
        /// </summary>
        internal static string tag_path {
            get {
                return ResourceManager.GetString("tag_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path element at the specified index (e.g. for C:\F1\MySolutionFolder\MySolution.sln, [path:0] = C:\, [path:1] = C:\F1).
        /// </summary>
        internal static string tag_pathX {
            get {
                return ResourceManager.GetString("tag_pathX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path segment over the specified range (e.g. for C:\F1\MySolutionFolder\MySolution.sln, [path:0:2] = C:\F1\MySolutionFolder, [path:2:0] = MySolutionFolder\F1\C:).
        /// </summary>
        internal static string tag_pathXY {
            get {
                return ResourceManager.GetString("tag_pathXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current platform name (e.g. x86)..
        /// </summary>
        internal static string tag_platformName {
            get {
                return ResourceManager.GetString("tag_platformName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active project name..
        /// </summary>
        internal static string tag_projectName {
            get {
                return ResourceManager.GetString("tag_projectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active solution name..
        /// </summary>
        internal static string tag_solutionName {
            get {
                return ResourceManager.GetString("tag_solutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major version of Visual Studio (e.g. 9, 10, 11, 12, 14...)..
        /// </summary>
        internal static string tag_vsMajorVersion {
            get {
                return ResourceManager.GetString("tag_vsMajorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major version of Visual Studio, in year form (e.g. 2008, 2010, 2012, 2013, 2015...)..
        /// </summary>
        internal static string tag_vsMajorVersionYear {
            get {
                return ResourceManager.GetString("tag_vsMajorVersionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Team Foundation Server (TFS) workspace name..
        /// </summary>
        internal static string tag_workspaceName {
            get {
                return ResourceManager.GetString("tag_workspaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Team Foundation Server (TFS) workspace owner name..
        /// </summary>
        internal static string tag_workspaceOwnerName {
            get {
                return ResourceManager.GetString("tag_workspaceOwnerName", resourceCulture);
            }
        }
    }
}
