//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErwinMayerLabs.RenameVSWindowTitle {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErwinMayerLabs.RenameVSWindowTitle.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //http://stackoverflow.com/questions/200162/allow-only-copy-paste-context-menu-in-system-windows-forms-webbrowser-control/200194#200194
        /////&lt;div id=&apos;ContextMenu&apos; style=&apos;display: none; z-index: 1000; padding: 1px 10px; background-color: white; border: 2px solid lightgreen; position: absolute;&apos;&gt;&lt;a href=&apos;#&apos; id=&apos;CopyBtn&apos; style=&apos;display: block; color: black; text-decoration: none;&apos;&gt;Copy&lt;/a&gt;&lt;/div&gt;
        ///
        ///function selectText(obj) { // adapted from Denis Sadowski (via StackOverflow.com)
        ///    var range;
        ///    if (document [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string script {
            get {
                return ResourceManager.GetString("script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///	background: #fafafa;
        ///	color: #444;
        ///	font: 100%/30px &apos;Helvetica Neue&apos;, helvetica, arial, sans-serif;
        ///}
        ///
        ///h1 {
        ///  font-size: 15pt;
        ///  margin-bottom: 10px;
        ///  font-weight: bold;
        ///}
        ///
        ///strong {
        ///	font-weight: bold; 
        ///}
        ///
        ///em {
        ///	font-style: italic; 
        ///}
        ///
        ///table {
        ///	background: #f5f5f5;
        ///	font-size: 10pt;
        ///	line-height: 24px;
        ///	text-align: left;
        ///}	
        ///
        ///th {
        ///	background: #333;
        ///	border-left: 1px solid #555;
        ///	border-right: 1px solid #777;
        ///	border-top: 1px solid #555;
        ///	border-bottom: 1px solid #333 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
    }
}
